update all the helper scripts

diff --git a/gen b/gen
--- a/gen
+++ b/gen
@@ -1,27 +1,35 @@
 #!/bin/bash
-# compile the pyjamas AUR app into deployable JS
+# compile pyjamas AUR app into deployable JS application
 
-orig_pwd="$(pwd)" && cd "$(dirname ${0})" && base="$(pwd)" || { echo 'problems...'; exit 1; }
+exec 3> /dev/null
 
-# workaround for public folder issue in pyjs
-if [ ! -L ${base}/pub/_pyjs.js -a ! -e ${base}/pub/_pyjs.js ]; then
-    ln -s ../.pyjs/pyjs/src/pyjs/builtin/public/_pyjs.js ${base}/pub
+spushd () { pushd ${1} >&3; }
+spopd () { popd >&3; }
+
+spushd $(dirname ${0})
+
+PYJS_BOX_EXEC=$(pwd)/.pyjs/bin/pyjsbuild
+PYJS_SYS_EXEC=$(which pyjsbuild 2>&-)
+
+if [ ! -e "${PYJS_BOX_EXEC}" -a ! -e "${PYJS_SYS_EXEC}" ]; then
+    ./init 'true' || { echo 'could not find PYJS_EXEC (pyjsbuild)'; exit 1; }
+    PYJS_EXEC=${PYJS_BOX_EXEC}
+elif [ -e "${PYJS_BOX_EXEC}" ]; then
+    PYJS_EXEC=${PYJS_BOX_EXEC}
+else
+    PYJS_EXEC=${PYJS_SYS_EXEC}
 fi
 
-# don't remove the folder; messes up SimpleHTTPServer (it's it the folder)
-rm -rf ${base}/out/*
-cd ${base}/src
+# don't remove the folder; SimpleHTTPServer could be running
+rm -rf out/*
 
-if ! [ -e ${base}/.pyjs/bin/pyjsbuild ]; then
-    ${base}/init || { echo 'problem building'; exit 1; }
-fi
+# build AUR
+spushd src
+${PYJS_EXEC} -mcO --bootstrap-file="Aur.js" --output="../out" Aur.py
+spopd
 
-${base}/.pyjs/bin/pyjsbuild \
-    -mcO \
-    --bootstrap-file="Aur.js" \
-    --public-folder="${base}/pub" \
-    --output="${base}/out" \
-    Aur.py
+# copy pub folder to out
+cp -R pub/* out
 
-cd ${orig_pwd}
+spopd
 exit 0
